name = "glmatrix"
version = "0.1.0"
licences = ["Apache-2.0"]
repository = { type = "github", user = "haruki7049", repo = "glmatrix" }

# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
gleam_httpc = ">= 4.1.0 and < 5.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
